# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d6ac28c1f263ca9958560119045be948cf02f8476ab9546fb5ded3acae8257a6733a170a8c95703f6d4571c9c704925b20856b86197b7c3ef3ee92f652f9ff19

test:
  secret_key_base: da5f34aa68f0bda63e1e5704a2662f140ec6eb4ec4bb212e736a80857e1a5556110982fc5845f29d6477e7f6485d286e7f77c474b03abe0128e23266ae26117c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
